---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: buildkite-agent
stringData:

  # Database settings
  PGUSER: ...
  PGPASSWORD: ...
  PGHOST: ha-postgres
  PGPORT: "5432"
  PGDATABASE: buildkite-agent

  # The symmetric key
  AES256_KEY: ...